### ISSUE TITLE
well that was easy

### ISSUE THREAD

**Issue by TechStudent10** [Kendall-Does-Coding-Websites/free-hosting-via-pr#2]
no legit that was easy

also this might be useful, but idk.

**Comment by KendallDoesCoding** [comment]
> no legit that was easy
> 
> also this might be useful, but idk.

Well, if multiple people keep on using this then I will have a issue with Netlify lol, I can only deploy 300 minutes of stuff for a period of a month I think, my most deployed was last month with 26 mins. Each deploy takes 2 secs, but we only have 18000 for a free plan. So, with 9k deploys it will be done, not that we will hit 9k deploys but yeah, that's a issue lol.

But this is just to do basic testings and stuff to HTML, CSS and JS code.

**Comment by KendallDoesCoding** [comment]
So, as mentioned the maximum deploy secs I used was 1560/9000, which was from November 24th to December 24th. But, that was during my big project, mogul-christmas. So ig to use 9000 secs it will really take huge projects but this is good for testings and stuff as mentioned. And eh, I can always make new netlify accounts.

**Comment by KendallDoesCoding** [comment]
But, that's only netlify. I dont think heroku has a deploy limit. So, I gotta do some research. Also, coz this is on my main Netlify account it can also interfere with my deploys and stuff, because each deploy takes 2secs then it goes to the next one. So after I do research about heroku, I may setup this project via heroku and continue to use Netlify though for my other projects.

**Comment by TechStudent10** [comment]
Heroku can't deploy via PR.

**Comment by KendallDoesCoding** [comment]
> Heroku can't deploy via PR.

Oh, then maybe I can try something like Vercel, if it works for HTML. I gotta do some research.

**Comment by KendallDoesCoding** [comment]
Yep, shifted over this project to Vercel. Netlify still does checks on PR's but now it doesn't comment, only vercel does as you can see in #3

**Comment by KendallDoesCoding** [comment]
Closing this now...
